config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  root to: 'products#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validate :title_is_shorter_than_description
  before_validation :strip_html_from_description
  before_save :lower_case

  def strip_html_from_description
    self.description = ActionView::Base.full_sanitizer.sanitize(self.description)
  end

  def lower_case
    self.title = title.downcase
  end

  def title_is_shorter_than_description
    return if title.blank? or description.blank?
    if description.length < title.length
      errors.add(:title, 'Title must be shorter than description')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product_by_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
    return redirect_to products_path if @product.save
    flash.now[:notice] = 'Fail'
    render :new
  end

  def new
    @product = Product.new
  end

  def edit    
  end

  def update    
    return redirect_to products_path, notice: 'success' if @product.update(product_params)
    flash.now[:notice] = 'Wrong input.'
    render :edit
  end

  def show    
  end

  def destroy    
    flash[:notice] = 'Delete fail.'
    flash[:notice] = 'Success' if @product.destroy
    return redirect_to products_path
  end

  private
  def get_product_by_id
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Railstdd
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body

    - flash.each do |name, msg|
      = content_tag :div, msg, class: name

    = yield
    = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/products/edit.html.slim
h1 Edit product

= semantic_form_for @product do |p|
  = p.input :title
  = p.input :description
  = p.input :price, min: 0.01
  = p.input :category
  = p.action :submit

app/views/products/index.html.slim
h1 All products
table
  tr
    th Title
    th Description
    th Price
    th
    th

  - @products.each do |product|
    tr
      td = link_to product.title, product_path(product)
      td = product.description
      td = product.price
      td = link_to 'Edit', edit_product_path(product)
      td = link_to 'Delete', product_path(product), method: :delete
= link_to 'Create a product', new_product_path

app/views/products/new.html.slim
h1 Create Product

= semantic_form_for @product do |p|
  = p.input :title
  = p.input :description
  = p.input :price, min: 0.01
  = p.input :category
  = p.action :submit, label: 'Submit'

app/views/products/show.html.slim
h1 Description of selected product

h2 = @product.title
p Price: #{@product.price}
p Description: #{@product.description}